@baseUrl=http://localhost:3000/v1




GET {{baseUrl}}/users/78

###

GET {{baseUrl}}/users/?limit=10


###

POST  {{baseUrl}}/users
Content-Type: application/json

{
    "firstname": "test_first_name",
    "lastname" : "test_last_name",
    "email":"test84@gmail.com",
    "password" : "1234",
    "confirmPassword" : "1234",
    "gender" : "male",
    "phone_number" : "04546574984"
    
}

###

PATCH  {{baseUrl}}/users
Content-Type: application/json

{
    "id" : 78,
    "phone_number" : "125874"
    
}

###

DELETE {{baseUrl}}/users
Content-Type: application/json

{
    "id" : 80
}


### ---- EVENT
GET {{baseUrl}}/events/9
###
GET {{baseUrl}}/events/?limit=10
