@baseUrl=http://localhost:3000/v1

GET {{baseUrl}}/users/11

###

GET {{baseUrl}}/users/?limit=3

###

POST  {{baseUrl}}/users
Content-Type: application/json

{
    "firstname": "test_first_name",
    "lastname" : "test_last_name",
    "email":"test85@gmail.com",
    "password" : "1234",
    "confirmPassword" : "1234",
    "gender" : "male",
    "phone_number" : "04546574984"
    
}

###

PATCH  {{baseUrl}}/users
Content-Type: application/json

{
    "id" : 54,
    "phone_number" : "125874"
}
###

DELETE {{baseUrl}}/users
Content-Type: application/json

{
    "id" : 1
}


### ---- EVENT
## FIND ONE
GET {{baseUrl}}/events/16
### FIND ALL LIMI
GET {{baseUrl}}/events/?limit=10
### UPDATE EVENTS
PATCH  {{baseUrl}}/events
Content-Type: application/json

{
    "id" : 3,
    "title" : "bullshiiiit"
}
### DELETE
DELETE {{baseUrl}}/events
Content-Type: application/json

{
    "id" : 16
}
###


